name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-deploy:
    name: Build and Deploy Youtube Converter
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile launch.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: launch-executable
          path: dist/launch.exe

  release:
    needs: build-deploy
    runs-on: windows-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: launch-executable

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This is the release of version ${{ github.ref_name }}.
            The executable is attached below.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move executable to root
        run: |
          mv dist/launch.exe .

      - name: Upload executable to release
        uses: softprops/action-gh-release@v1
        with:
          files: launch-executable/launch.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}