name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile youtubeConverter.py

      - name: List files (debug)
        run: Get-ChildItem -Recurse dist

      - name: Create GitHub Release and upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This is the release of version ${{ github.ref_name }}.
            The executable is attached below.
          files: dist/youtubeConverter.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
