name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --windowed --name youtubeConverter youtubeConverter.py

      - name: Rename and Zip Executable
        run: |
          cd dist
          powershell Compress-Archive -Path youtubeConverter.exe -DestinationPath youtubeConverter.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🎉 Version ${{ github.ref_name }} is out!

            💾 Download `youtubeConverter.zip` and extract it before running.

            ⚠️ If your antivirus flags it, you may need to allow the executable. It’s safe as long as it's from this repository.
          files: dist/youtubeConverter.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}