name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Clean previous builds
        run: |
          if (Test-Path "dist") { Remove-Item -Recurse -Force "dist" }
          if (Test-Path "build") { Remove-Item -Recurse -Force "build" }
          if (Test-Path "*.spec") { Remove-Item -Force "*.spec" }

      - name: Build executable with PyInstaller
        shell: cmd
        run: |
          pyinstaller --onefile ^
            --windowed ^
            --name youtubeConverter ^
            --clean ^
            --noconfirm ^
            youtubeConverter.py

      - name: Calculate file hash
        run: |
          cd dist
          $hash = Get-FileHash youtubeConverter.exe -Algorithm SHA256
          $hash.Hash | Out-File -FilePath youtubeConverter.exe.sha256

      - name: Create ZIP with documentation
        run: |
          cd dist
          echo "YouTube Converter v${{ github.ref_name }}" > README.txt
          echo "" >> README.txt
          echo "This is a legitimate YouTube converter tool." >> README.txt
          echo "Source code: https://github.com/${{ github.repository }}" >> README.txt
          echo "SHA256: $(Get-Content youtubeConverter.exe.sha256)" >> README.txt
          echo "" >> README.txt
          echo "If your antivirus flags this file, it's a false positive." >> README.txt
          echo "You can verify the hash above matches the original." >> README.txt
          powershell Compress-Archive -Path youtubeConverter.exe,README.txt,youtubeConverter.exe.sha256 -DestinationPath youtubeConverter.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🎉 Version ${{ github.ref_name }} is out!

            💾 Download `youtubeConverter.zip` and extract it before running.
            
            **File Verification**: 
            - SHA256 hash is included in the ZIP for verification
            - Source code is fully available in this repository
            
            **Antivirus Warning**: This may trigger false positives due to PyInstaller packaging.
            The executable is safe when downloaded from official GitHub releases.
            
            **Security**: 
            - Built automatically via GitHub Actions
            - No manual modifications to the executable
            - Verify the SHA256 hash if concerned about integrity

            **Installation**: Extract the ZIP file and run youtubeConverter.exe
          files: |
            dist/youtubeConverter.zip
            dist/youtubeConverter.exe.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}